# coding: utf-8

"""
    HEAppE Web API

    HEAppE middleware API v2  # noqa: E501

    OpenAPI spec version: v2
    Contact: support.heappe@it4i.cz
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from heappeac.api_client import ApiClient


class JobReportingApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def heappe_job_reporting_get_resource_usage_report_for_job_post(self, **kwargs):  # noqa: E501
        """Get resource usage for executed job  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.heappe_job_reporting_get_resource_usage_report_for_job_post(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param GetResourceUsageReportForJob body:
        :return: SubmittedJobInfoUsageReportExt
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.heappe_job_reporting_get_resource_usage_report_for_job_post_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.heappe_job_reporting_get_resource_usage_report_for_job_post_with_http_info(**kwargs)  # noqa: E501
            return data

    def heappe_job_reporting_get_resource_usage_report_for_job_post_with_http_info(self, **kwargs):  # noqa: E501
        """Get resource usage for executed job  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.heappe_job_reporting_get_resource_usage_report_for_job_post_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param GetResourceUsageReportForJob body:
        :return: SubmittedJobInfoUsageReportExt
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method heappe_job_reporting_get_resource_usage_report_for_job_post" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json-patch+json', 'application/json', 'text/json', 'application/*+json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/heappe/JobReporting/GetResourceUsageReportForJob', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='SubmittedJobInfoUsageReportExt',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def heappe_job_reporting_get_user_group_resource_usage_report_post(self, **kwargs):  # noqa: E501
        """Get resource usage for user group  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.heappe_job_reporting_get_user_group_resource_usage_report_post(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param GetUserGroupResourceUsageReportView body:
        :return: UserGroupResourceUsageReportExt
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.heappe_job_reporting_get_user_group_resource_usage_report_post_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.heappe_job_reporting_get_user_group_resource_usage_report_post_with_http_info(**kwargs)  # noqa: E501
            return data

    def heappe_job_reporting_get_user_group_resource_usage_report_post_with_http_info(self, **kwargs):  # noqa: E501
        """Get resource usage for user group  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.heappe_job_reporting_get_user_group_resource_usage_report_post_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param GetUserGroupResourceUsageReportView body:
        :return: UserGroupResourceUsageReportExt
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method heappe_job_reporting_get_user_group_resource_usage_report_post" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json-patch+json', 'application/json', 'text/json', 'application/*+json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/heappe/JobReporting/GetUserGroupResourceUsageReport', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='UserGroupResourceUsageReportExt',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def heappe_job_reporting_get_user_resource_usage_report_post(self, **kwargs):  # noqa: E501
        """Get resource usage report for user  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.heappe_job_reporting_get_user_resource_usage_report_post(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param GetUserResourceUsageReportView body:
        :return: UserResourceUsageReportExt
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.heappe_job_reporting_get_user_resource_usage_report_post_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.heappe_job_reporting_get_user_resource_usage_report_post_with_http_info(**kwargs)  # noqa: E501
            return data

    def heappe_job_reporting_get_user_resource_usage_report_post_with_http_info(self, **kwargs):  # noqa: E501
        """Get resource usage report for user  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.heappe_job_reporting_get_user_resource_usage_report_post_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param GetUserResourceUsageReportView body:
        :return: UserResourceUsageReportExt
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method heappe_job_reporting_get_user_resource_usage_report_post" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json-patch+json', 'application/json', 'text/json', 'application/*+json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/heappe/JobReporting/GetUserResourceUsageReport', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='UserResourceUsageReportExt',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def heappe_job_reporting_list_adaptor_user_groups_post(self, **kwargs):  # noqa: E501
        """Get user groups  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.heappe_job_reporting_list_adaptor_user_groups_post(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param ListAdaptorUserGroupsView body:
        :return: list[AdaptorUserGroupExt]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.heappe_job_reporting_list_adaptor_user_groups_post_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.heappe_job_reporting_list_adaptor_user_groups_post_with_http_info(**kwargs)  # noqa: E501
            return data

    def heappe_job_reporting_list_adaptor_user_groups_post_with_http_info(self, **kwargs):  # noqa: E501
        """Get user groups  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.heappe_job_reporting_list_adaptor_user_groups_post_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param ListAdaptorUserGroupsView body:
        :return: list[AdaptorUserGroupExt]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method heappe_job_reporting_list_adaptor_user_groups_post" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json-patch+json', 'application/json', 'text/json', 'application/*+json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/heappe/JobReporting/ListAdaptorUserGroups', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[AdaptorUserGroupExt]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
