# coding: utf-8

"""
    HEAppE Web API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class TaskSpecificationExt(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'min_cores': 'int',
        'max_cores': 'int',
        'walltime_limit': 'int',
        'required_nodes': 'str',
        'is_exclusive': 'bool',
        'is_rerunnable': 'bool',
        'standard_input_file': 'str',
        'standard_output_file': 'str',
        'standard_error_file': 'str',
        'progress_file': 'str',
        'log_file': 'str',
        'cluster_task_subdirectory': 'str',
        'command_template_id': 'int',
        'environment_variables': 'list[EnvironmentVariableExt]',
        'depends_on': 'list[TaskSpecificationExt]',
        'template_parameter_values': 'list[CommandTemplateParameterValueExt]'
    }

    attribute_map = {
        'name': 'name',
        'min_cores': 'minCores',
        'max_cores': 'maxCores',
        'walltime_limit': 'walltimeLimit',
        'required_nodes': 'requiredNodes',
        'is_exclusive': 'isExclusive',
        'is_rerunnable': 'isRerunnable',
        'standard_input_file': 'standardInputFile',
        'standard_output_file': 'standardOutputFile',
        'standard_error_file': 'standardErrorFile',
        'progress_file': 'progressFile',
        'log_file': 'logFile',
        'cluster_task_subdirectory': 'clusterTaskSubdirectory',
        'command_template_id': 'commandTemplateId',
        'environment_variables': 'environmentVariables',
        'depends_on': 'dependsOn',
        'template_parameter_values': 'templateParameterValues'
    }

    def __init__(self, name=None, min_cores=None, max_cores=None, walltime_limit=None, required_nodes=None, is_exclusive=None, is_rerunnable=None, standard_input_file=None, standard_output_file=None, standard_error_file=None, progress_file=None, log_file=None, cluster_task_subdirectory=None, command_template_id=None, environment_variables=None, depends_on=None, template_parameter_values=None):  # noqa: E501
        """TaskSpecificationExt - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._min_cores = None
        self._max_cores = None
        self._walltime_limit = None
        self._required_nodes = None
        self._is_exclusive = None
        self._is_rerunnable = None
        self._standard_input_file = None
        self._standard_output_file = None
        self._standard_error_file = None
        self._progress_file = None
        self._log_file = None
        self._cluster_task_subdirectory = None
        self._command_template_id = None
        self._environment_variables = None
        self._depends_on = None
        self._template_parameter_values = None
        self.discriminator = None
        if name is not None:
            self.name = name
        if min_cores is not None:
            self.min_cores = min_cores
        if max_cores is not None:
            self.max_cores = max_cores
        if walltime_limit is not None:
            self.walltime_limit = walltime_limit
        if required_nodes is not None:
            self.required_nodes = required_nodes
        if is_exclusive is not None:
            self.is_exclusive = is_exclusive
        if is_rerunnable is not None:
            self.is_rerunnable = is_rerunnable
        if standard_input_file is not None:
            self.standard_input_file = standard_input_file
        if standard_output_file is not None:
            self.standard_output_file = standard_output_file
        if standard_error_file is not None:
            self.standard_error_file = standard_error_file
        if progress_file is not None:
            self.progress_file = progress_file
        if log_file is not None:
            self.log_file = log_file
        if cluster_task_subdirectory is not None:
            self.cluster_task_subdirectory = cluster_task_subdirectory
        if command_template_id is not None:
            self.command_template_id = command_template_id
        if environment_variables is not None:
            self.environment_variables = environment_variables
        if depends_on is not None:
            self.depends_on = depends_on
        if template_parameter_values is not None:
            self.template_parameter_values = template_parameter_values

    @property
    def name(self):
        """Gets the name of this TaskSpecificationExt.  # noqa: E501


        :return: The name of this TaskSpecificationExt.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this TaskSpecificationExt.


        :param name: The name of this TaskSpecificationExt.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def min_cores(self):
        """Gets the min_cores of this TaskSpecificationExt.  # noqa: E501


        :return: The min_cores of this TaskSpecificationExt.  # noqa: E501
        :rtype: int
        """
        return self._min_cores

    @min_cores.setter
    def min_cores(self, min_cores):
        """Sets the min_cores of this TaskSpecificationExt.


        :param min_cores: The min_cores of this TaskSpecificationExt.  # noqa: E501
        :type: int
        """

        self._min_cores = min_cores

    @property
    def max_cores(self):
        """Gets the max_cores of this TaskSpecificationExt.  # noqa: E501


        :return: The max_cores of this TaskSpecificationExt.  # noqa: E501
        :rtype: int
        """
        return self._max_cores

    @max_cores.setter
    def max_cores(self, max_cores):
        """Sets the max_cores of this TaskSpecificationExt.


        :param max_cores: The max_cores of this TaskSpecificationExt.  # noqa: E501
        :type: int
        """

        self._max_cores = max_cores

    @property
    def walltime_limit(self):
        """Gets the walltime_limit of this TaskSpecificationExt.  # noqa: E501


        :return: The walltime_limit of this TaskSpecificationExt.  # noqa: E501
        :rtype: int
        """
        return self._walltime_limit

    @walltime_limit.setter
    def walltime_limit(self, walltime_limit):
        """Sets the walltime_limit of this TaskSpecificationExt.


        :param walltime_limit: The walltime_limit of this TaskSpecificationExt.  # noqa: E501
        :type: int
        """

        self._walltime_limit = walltime_limit

    @property
    def required_nodes(self):
        """Gets the required_nodes of this TaskSpecificationExt.  # noqa: E501


        :return: The required_nodes of this TaskSpecificationExt.  # noqa: E501
        :rtype: str
        """
        return self._required_nodes

    @required_nodes.setter
    def required_nodes(self, required_nodes):
        """Sets the required_nodes of this TaskSpecificationExt.


        :param required_nodes: The required_nodes of this TaskSpecificationExt.  # noqa: E501
        :type: str
        """

        self._required_nodes = required_nodes

    @property
    def is_exclusive(self):
        """Gets the is_exclusive of this TaskSpecificationExt.  # noqa: E501


        :return: The is_exclusive of this TaskSpecificationExt.  # noqa: E501
        :rtype: bool
        """
        return self._is_exclusive

    @is_exclusive.setter
    def is_exclusive(self, is_exclusive):
        """Sets the is_exclusive of this TaskSpecificationExt.


        :param is_exclusive: The is_exclusive of this TaskSpecificationExt.  # noqa: E501
        :type: bool
        """

        self._is_exclusive = is_exclusive

    @property
    def is_rerunnable(self):
        """Gets the is_rerunnable of this TaskSpecificationExt.  # noqa: E501


        :return: The is_rerunnable of this TaskSpecificationExt.  # noqa: E501
        :rtype: bool
        """
        return self._is_rerunnable

    @is_rerunnable.setter
    def is_rerunnable(self, is_rerunnable):
        """Sets the is_rerunnable of this TaskSpecificationExt.


        :param is_rerunnable: The is_rerunnable of this TaskSpecificationExt.  # noqa: E501
        :type: bool
        """

        self._is_rerunnable = is_rerunnable

    @property
    def standard_input_file(self):
        """Gets the standard_input_file of this TaskSpecificationExt.  # noqa: E501


        :return: The standard_input_file of this TaskSpecificationExt.  # noqa: E501
        :rtype: str
        """
        return self._standard_input_file

    @standard_input_file.setter
    def standard_input_file(self, standard_input_file):
        """Sets the standard_input_file of this TaskSpecificationExt.


        :param standard_input_file: The standard_input_file of this TaskSpecificationExt.  # noqa: E501
        :type: str
        """

        self._standard_input_file = standard_input_file

    @property
    def standard_output_file(self):
        """Gets the standard_output_file of this TaskSpecificationExt.  # noqa: E501


        :return: The standard_output_file of this TaskSpecificationExt.  # noqa: E501
        :rtype: str
        """
        return self._standard_output_file

    @standard_output_file.setter
    def standard_output_file(self, standard_output_file):
        """Sets the standard_output_file of this TaskSpecificationExt.


        :param standard_output_file: The standard_output_file of this TaskSpecificationExt.  # noqa: E501
        :type: str
        """

        self._standard_output_file = standard_output_file

    @property
    def standard_error_file(self):
        """Gets the standard_error_file of this TaskSpecificationExt.  # noqa: E501


        :return: The standard_error_file of this TaskSpecificationExt.  # noqa: E501
        :rtype: str
        """
        return self._standard_error_file

    @standard_error_file.setter
    def standard_error_file(self, standard_error_file):
        """Sets the standard_error_file of this TaskSpecificationExt.


        :param standard_error_file: The standard_error_file of this TaskSpecificationExt.  # noqa: E501
        :type: str
        """

        self._standard_error_file = standard_error_file

    @property
    def progress_file(self):
        """Gets the progress_file of this TaskSpecificationExt.  # noqa: E501


        :return: The progress_file of this TaskSpecificationExt.  # noqa: E501
        :rtype: str
        """
        return self._progress_file

    @progress_file.setter
    def progress_file(self, progress_file):
        """Sets the progress_file of this TaskSpecificationExt.


        :param progress_file: The progress_file of this TaskSpecificationExt.  # noqa: E501
        :type: str
        """

        self._progress_file = progress_file

    @property
    def log_file(self):
        """Gets the log_file of this TaskSpecificationExt.  # noqa: E501


        :return: The log_file of this TaskSpecificationExt.  # noqa: E501
        :rtype: str
        """
        return self._log_file

    @log_file.setter
    def log_file(self, log_file):
        """Sets the log_file of this TaskSpecificationExt.


        :param log_file: The log_file of this TaskSpecificationExt.  # noqa: E501
        :type: str
        """

        self._log_file = log_file

    @property
    def cluster_task_subdirectory(self):
        """Gets the cluster_task_subdirectory of this TaskSpecificationExt.  # noqa: E501


        :return: The cluster_task_subdirectory of this TaskSpecificationExt.  # noqa: E501
        :rtype: str
        """
        return self._cluster_task_subdirectory

    @cluster_task_subdirectory.setter
    def cluster_task_subdirectory(self, cluster_task_subdirectory):
        """Sets the cluster_task_subdirectory of this TaskSpecificationExt.


        :param cluster_task_subdirectory: The cluster_task_subdirectory of this TaskSpecificationExt.  # noqa: E501
        :type: str
        """

        self._cluster_task_subdirectory = cluster_task_subdirectory

    @property
    def command_template_id(self):
        """Gets the command_template_id of this TaskSpecificationExt.  # noqa: E501


        :return: The command_template_id of this TaskSpecificationExt.  # noqa: E501
        :rtype: int
        """
        return self._command_template_id

    @command_template_id.setter
    def command_template_id(self, command_template_id):
        """Sets the command_template_id of this TaskSpecificationExt.


        :param command_template_id: The command_template_id of this TaskSpecificationExt.  # noqa: E501
        :type: int
        """

        self._command_template_id = command_template_id

    @property
    def environment_variables(self):
        """Gets the environment_variables of this TaskSpecificationExt.  # noqa: E501


        :return: The environment_variables of this TaskSpecificationExt.  # noqa: E501
        :rtype: list[EnvironmentVariableExt]
        """
        return self._environment_variables

    @environment_variables.setter
    def environment_variables(self, environment_variables):
        """Sets the environment_variables of this TaskSpecificationExt.


        :param environment_variables: The environment_variables of this TaskSpecificationExt.  # noqa: E501
        :type: list[EnvironmentVariableExt]
        """

        self._environment_variables = environment_variables

    @property
    def depends_on(self):
        """Gets the depends_on of this TaskSpecificationExt.  # noqa: E501


        :return: The depends_on of this TaskSpecificationExt.  # noqa: E501
        :rtype: list[TaskSpecificationExt]
        """
        return self._depends_on

    @depends_on.setter
    def depends_on(self, depends_on):
        """Sets the depends_on of this TaskSpecificationExt.


        :param depends_on: The depends_on of this TaskSpecificationExt.  # noqa: E501
        :type: list[TaskSpecificationExt]
        """

        self._depends_on = depends_on

    @property
    def template_parameter_values(self):
        """Gets the template_parameter_values of this TaskSpecificationExt.  # noqa: E501


        :return: The template_parameter_values of this TaskSpecificationExt.  # noqa: E501
        :rtype: list[CommandTemplateParameterValueExt]
        """
        return self._template_parameter_values

    @template_parameter_values.setter
    def template_parameter_values(self, template_parameter_values):
        """Sets the template_parameter_values of this TaskSpecificationExt.


        :param template_parameter_values: The template_parameter_values of this TaskSpecificationExt.  # noqa: E501
        :type: list[CommandTemplateParameterValueExt]
        """

        self._template_parameter_values = template_parameter_values

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TaskSpecificationExt, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TaskSpecificationExt):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
