# coding: utf-8

"""
    HEAppE Web API

    HEAppE middleware API v4.2.1  # noqa: E501

    OpenAPI spec version: v4.2.1
    Contact: support.heappe@it4i.cz
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AuthenticateUserOpenIdOpenStackModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'credentials': 'OpenIdCredentialsExt',
        'project_id': 'int'
    }

    attribute_map = {
        'credentials': 'Credentials',
        'project_id': 'ProjectId'
    }

    def __init__(self, credentials=None, project_id=None):  # noqa: E501
        """AuthenticateUserOpenIdOpenStackModel - a model defined in Swagger"""  # noqa: E501
        self._credentials = None
        self._project_id = None
        self.discriminator = None
        if credentials is not None:
            self.credentials = credentials
        if project_id is not None:
            self.project_id = project_id

    @property
    def credentials(self):
        """Gets the credentials of this AuthenticateUserOpenIdOpenStackModel.  # noqa: E501


        :return: The credentials of this AuthenticateUserOpenIdOpenStackModel.  # noqa: E501
        :rtype: OpenIdCredentialsExt
        """
        return self._credentials

    @credentials.setter
    def credentials(self, credentials):
        """Sets the credentials of this AuthenticateUserOpenIdOpenStackModel.


        :param credentials: The credentials of this AuthenticateUserOpenIdOpenStackModel.  # noqa: E501
        :type: OpenIdCredentialsExt
        """

        self._credentials = credentials

    @property
    def project_id(self):
        """Gets the project_id of this AuthenticateUserOpenIdOpenStackModel.  # noqa: E501


        :return: The project_id of this AuthenticateUserOpenIdOpenStackModel.  # noqa: E501
        :rtype: int
        """
        return self._project_id

    @project_id.setter
    def project_id(self, project_id):
        """Sets the project_id of this AuthenticateUserOpenIdOpenStackModel.


        :param project_id: The project_id of this AuthenticateUserOpenIdOpenStackModel.  # noqa: E501
        :type: int
        """

        self._project_id = project_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AuthenticateUserOpenIdOpenStackModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AuthenticateUserOpenIdOpenStackModel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
