# coding: utf-8

"""
    HEAppE Web API

    HEAppE middleware API v4.2.1  # noqa: E501

    OpenAPI spec version: v4.2.1
    Contact: support.heappe@it4i.cz
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ClusterNodeTypeDetailedReportExt(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'total_usage': 'float',
        'name': 'str',
        'description': 'str',
        'queue_name': 'str',
        'jobs': 'list[JobDetailedReportExt]'
    }

    attribute_map = {
        'id': 'Id',
        'total_usage': 'TotalUsage',
        'name': 'Name',
        'description': 'Description',
        'queue_name': 'QueueName',
        'jobs': 'Jobs'
    }

    def __init__(self, id=None, total_usage=None, name=None, description=None, queue_name=None, jobs=None):  # noqa: E501
        """ClusterNodeTypeDetailedReportExt - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._total_usage = None
        self._name = None
        self._description = None
        self._queue_name = None
        self._jobs = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if total_usage is not None:
            self.total_usage = total_usage
        if name is not None:
            self.name = name
        if description is not None:
            self.description = description
        if queue_name is not None:
            self.queue_name = queue_name
        if jobs is not None:
            self.jobs = jobs

    @property
    def id(self):
        """Gets the id of this ClusterNodeTypeDetailedReportExt.  # noqa: E501


        :return: The id of this ClusterNodeTypeDetailedReportExt.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ClusterNodeTypeDetailedReportExt.


        :param id: The id of this ClusterNodeTypeDetailedReportExt.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def total_usage(self):
        """Gets the total_usage of this ClusterNodeTypeDetailedReportExt.  # noqa: E501


        :return: The total_usage of this ClusterNodeTypeDetailedReportExt.  # noqa: E501
        :rtype: float
        """
        return self._total_usage

    @total_usage.setter
    def total_usage(self, total_usage):
        """Sets the total_usage of this ClusterNodeTypeDetailedReportExt.


        :param total_usage: The total_usage of this ClusterNodeTypeDetailedReportExt.  # noqa: E501
        :type: float
        """

        self._total_usage = total_usage

    @property
    def name(self):
        """Gets the name of this ClusterNodeTypeDetailedReportExt.  # noqa: E501


        :return: The name of this ClusterNodeTypeDetailedReportExt.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ClusterNodeTypeDetailedReportExt.


        :param name: The name of this ClusterNodeTypeDetailedReportExt.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def description(self):
        """Gets the description of this ClusterNodeTypeDetailedReportExt.  # noqa: E501


        :return: The description of this ClusterNodeTypeDetailedReportExt.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this ClusterNodeTypeDetailedReportExt.


        :param description: The description of this ClusterNodeTypeDetailedReportExt.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def queue_name(self):
        """Gets the queue_name of this ClusterNodeTypeDetailedReportExt.  # noqa: E501


        :return: The queue_name of this ClusterNodeTypeDetailedReportExt.  # noqa: E501
        :rtype: str
        """
        return self._queue_name

    @queue_name.setter
    def queue_name(self, queue_name):
        """Sets the queue_name of this ClusterNodeTypeDetailedReportExt.


        :param queue_name: The queue_name of this ClusterNodeTypeDetailedReportExt.  # noqa: E501
        :type: str
        """

        self._queue_name = queue_name

    @property
    def jobs(self):
        """Gets the jobs of this ClusterNodeTypeDetailedReportExt.  # noqa: E501


        :return: The jobs of this ClusterNodeTypeDetailedReportExt.  # noqa: E501
        :rtype: list[JobDetailedReportExt]
        """
        return self._jobs

    @jobs.setter
    def jobs(self, jobs):
        """Sets the jobs of this ClusterNodeTypeDetailedReportExt.


        :param jobs: The jobs of this ClusterNodeTypeDetailedReportExt.  # noqa: E501
        :type: list[JobDetailedReportExt]
        """

        self._jobs = jobs

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ClusterNodeTypeDetailedReportExt, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ClusterNodeTypeDetailedReportExt):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
