# coding: utf-8

"""
    HEAppE Web API

    HEAppE middleware API v4.2.1  # noqa: E501

    OpenAPI spec version: v4.2.1
    Contact: support.heappe@it4i.cz
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CommandTemplateParameterValueExt(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'command_parameter_identifier': 'str',
        'parameter_value': 'str'
    }

    attribute_map = {
        'command_parameter_identifier': 'CommandParameterIdentifier',
        'parameter_value': 'ParameterValue'
    }

    def __init__(self, command_parameter_identifier=None, parameter_value=None):  # noqa: E501
        """CommandTemplateParameterValueExt - a model defined in Swagger"""  # noqa: E501
        self._command_parameter_identifier = None
        self._parameter_value = None
        self.discriminator = None
        if command_parameter_identifier is not None:
            self.command_parameter_identifier = command_parameter_identifier
        if parameter_value is not None:
            self.parameter_value = parameter_value

    @property
    def command_parameter_identifier(self):
        """Gets the command_parameter_identifier of this CommandTemplateParameterValueExt.  # noqa: E501


        :return: The command_parameter_identifier of this CommandTemplateParameterValueExt.  # noqa: E501
        :rtype: str
        """
        return self._command_parameter_identifier

    @command_parameter_identifier.setter
    def command_parameter_identifier(self, command_parameter_identifier):
        """Sets the command_parameter_identifier of this CommandTemplateParameterValueExt.


        :param command_parameter_identifier: The command_parameter_identifier of this CommandTemplateParameterValueExt.  # noqa: E501
        :type: str
        """

        self._command_parameter_identifier = command_parameter_identifier

    @property
    def parameter_value(self):
        """Gets the parameter_value of this CommandTemplateParameterValueExt.  # noqa: E501


        :return: The parameter_value of this CommandTemplateParameterValueExt.  # noqa: E501
        :rtype: str
        """
        return self._parameter_value

    @parameter_value.setter
    def parameter_value(self, parameter_value):
        """Sets the parameter_value of this CommandTemplateParameterValueExt.


        :param parameter_value: The parameter_value of this CommandTemplateParameterValueExt.  # noqa: E501
        :type: str
        """

        self._parameter_value = parameter_value

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CommandTemplateParameterValueExt, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CommandTemplateParameterValueExt):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
