# coding: utf-8

"""
    HEAppE Web API

    HEAppE middleware API v4.2.1  # noqa: E501

    OpenAPI spec version: v4.2.1
    Contact: support.heappe@it4i.cz
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ProjectDetailedReportExt(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'name': 'str',
        'description': 'str',
        'accounting_string': 'str',
        'total_usage': 'float',
        'start_date': 'datetime',
        'end_date': 'datetime',
        'clusters': 'list[ClusterDetailedReportExt]'
    }

    attribute_map = {
        'id': 'Id',
        'name': 'Name',
        'description': 'Description',
        'accounting_string': 'AccountingString',
        'total_usage': 'TotalUsage',
        'start_date': 'StartDate',
        'end_date': 'EndDate',
        'clusters': 'Clusters'
    }

    def __init__(self, id=None, name=None, description=None, accounting_string=None, total_usage=None, start_date=None, end_date=None, clusters=None):  # noqa: E501
        """ProjectDetailedReportExt - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._name = None
        self._description = None
        self._accounting_string = None
        self._total_usage = None
        self._start_date = None
        self._end_date = None
        self._clusters = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if description is not None:
            self.description = description
        if accounting_string is not None:
            self.accounting_string = accounting_string
        if total_usage is not None:
            self.total_usage = total_usage
        if start_date is not None:
            self.start_date = start_date
        if end_date is not None:
            self.end_date = end_date
        if clusters is not None:
            self.clusters = clusters

    @property
    def id(self):
        """Gets the id of this ProjectDetailedReportExt.  # noqa: E501


        :return: The id of this ProjectDetailedReportExt.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ProjectDetailedReportExt.


        :param id: The id of this ProjectDetailedReportExt.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this ProjectDetailedReportExt.  # noqa: E501


        :return: The name of this ProjectDetailedReportExt.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ProjectDetailedReportExt.


        :param name: The name of this ProjectDetailedReportExt.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def description(self):
        """Gets the description of this ProjectDetailedReportExt.  # noqa: E501


        :return: The description of this ProjectDetailedReportExt.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this ProjectDetailedReportExt.


        :param description: The description of this ProjectDetailedReportExt.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def accounting_string(self):
        """Gets the accounting_string of this ProjectDetailedReportExt.  # noqa: E501


        :return: The accounting_string of this ProjectDetailedReportExt.  # noqa: E501
        :rtype: str
        """
        return self._accounting_string

    @accounting_string.setter
    def accounting_string(self, accounting_string):
        """Sets the accounting_string of this ProjectDetailedReportExt.


        :param accounting_string: The accounting_string of this ProjectDetailedReportExt.  # noqa: E501
        :type: str
        """

        self._accounting_string = accounting_string

    @property
    def total_usage(self):
        """Gets the total_usage of this ProjectDetailedReportExt.  # noqa: E501


        :return: The total_usage of this ProjectDetailedReportExt.  # noqa: E501
        :rtype: float
        """
        return self._total_usage

    @total_usage.setter
    def total_usage(self, total_usage):
        """Sets the total_usage of this ProjectDetailedReportExt.


        :param total_usage: The total_usage of this ProjectDetailedReportExt.  # noqa: E501
        :type: float
        """

        self._total_usage = total_usage

    @property
    def start_date(self):
        """Gets the start_date of this ProjectDetailedReportExt.  # noqa: E501


        :return: The start_date of this ProjectDetailedReportExt.  # noqa: E501
        :rtype: datetime
        """
        return self._start_date

    @start_date.setter
    def start_date(self, start_date):
        """Sets the start_date of this ProjectDetailedReportExt.


        :param start_date: The start_date of this ProjectDetailedReportExt.  # noqa: E501
        :type: datetime
        """

        self._start_date = start_date

    @property
    def end_date(self):
        """Gets the end_date of this ProjectDetailedReportExt.  # noqa: E501


        :return: The end_date of this ProjectDetailedReportExt.  # noqa: E501
        :rtype: datetime
        """
        return self._end_date

    @end_date.setter
    def end_date(self, end_date):
        """Sets the end_date of this ProjectDetailedReportExt.


        :param end_date: The end_date of this ProjectDetailedReportExt.  # noqa: E501
        :type: datetime
        """

        self._end_date = end_date

    @property
    def clusters(self):
        """Gets the clusters of this ProjectDetailedReportExt.  # noqa: E501


        :return: The clusters of this ProjectDetailedReportExt.  # noqa: E501
        :rtype: list[ClusterDetailedReportExt]
        """
        return self._clusters

    @clusters.setter
    def clusters(self, clusters):
        """Sets the clusters of this ProjectDetailedReportExt.


        :param clusters: The clusters of this ProjectDetailedReportExt.  # noqa: E501
        :type: list[ClusterDetailedReportExt]
        """

        self._clusters = clusters

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ProjectDetailedReportExt, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProjectDetailedReportExt):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
