# coding: utf-8

"""
    HEAppE Web API

    HEAppE middleware API v4.2.1  # noqa: E501

    OpenAPI spec version: v4.2.1
    Contact: support.heappe@it4i.cz
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SubmittedTaskInfoExt(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'name': 'str',
        'state': 'TaskStateExt',
        'priority': 'TaskPriorityExt',
        'allocated_time': 'float',
        'allocated_core_ids': 'list[str]',
        'start_time': 'datetime',
        'end_time': 'datetime',
        'node_type': 'ClusterNodeTypeForTaskExt',
        'error_message': 'str',
        'cpu_hyper_threading': 'bool'
    }

    attribute_map = {
        'id': 'Id',
        'name': 'Name',
        'state': 'State',
        'priority': 'Priority',
        'allocated_time': 'AllocatedTime',
        'allocated_core_ids': 'AllocatedCoreIds',
        'start_time': 'StartTime',
        'end_time': 'EndTime',
        'node_type': 'NodeType',
        'error_message': 'ErrorMessage',
        'cpu_hyper_threading': 'CpuHyperThreading'
    }

    def __init__(self, id=None, name=None, state=None, priority=None, allocated_time=None, allocated_core_ids=None, start_time=None, end_time=None, node_type=None, error_message=None, cpu_hyper_threading=None):  # noqa: E501
        """SubmittedTaskInfoExt - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._name = None
        self._state = None
        self._priority = None
        self._allocated_time = None
        self._allocated_core_ids = None
        self._start_time = None
        self._end_time = None
        self._node_type = None
        self._error_message = None
        self._cpu_hyper_threading = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if state is not None:
            self.state = state
        if priority is not None:
            self.priority = priority
        if allocated_time is not None:
            self.allocated_time = allocated_time
        if allocated_core_ids is not None:
            self.allocated_core_ids = allocated_core_ids
        if start_time is not None:
            self.start_time = start_time
        if end_time is not None:
            self.end_time = end_time
        if node_type is not None:
            self.node_type = node_type
        if error_message is not None:
            self.error_message = error_message
        if cpu_hyper_threading is not None:
            self.cpu_hyper_threading = cpu_hyper_threading

    @property
    def id(self):
        """Gets the id of this SubmittedTaskInfoExt.  # noqa: E501


        :return: The id of this SubmittedTaskInfoExt.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this SubmittedTaskInfoExt.


        :param id: The id of this SubmittedTaskInfoExt.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this SubmittedTaskInfoExt.  # noqa: E501


        :return: The name of this SubmittedTaskInfoExt.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this SubmittedTaskInfoExt.


        :param name: The name of this SubmittedTaskInfoExt.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def state(self):
        """Gets the state of this SubmittedTaskInfoExt.  # noqa: E501


        :return: The state of this SubmittedTaskInfoExt.  # noqa: E501
        :rtype: TaskStateExt
        """
        return self._state

    @state.setter
    def state(self, state):
        """Sets the state of this SubmittedTaskInfoExt.


        :param state: The state of this SubmittedTaskInfoExt.  # noqa: E501
        :type: TaskStateExt
        """

        self._state = state

    @property
    def priority(self):
        """Gets the priority of this SubmittedTaskInfoExt.  # noqa: E501


        :return: The priority of this SubmittedTaskInfoExt.  # noqa: E501
        :rtype: TaskPriorityExt
        """
        return self._priority

    @priority.setter
    def priority(self, priority):
        """Sets the priority of this SubmittedTaskInfoExt.


        :param priority: The priority of this SubmittedTaskInfoExt.  # noqa: E501
        :type: TaskPriorityExt
        """

        self._priority = priority

    @property
    def allocated_time(self):
        """Gets the allocated_time of this SubmittedTaskInfoExt.  # noqa: E501


        :return: The allocated_time of this SubmittedTaskInfoExt.  # noqa: E501
        :rtype: float
        """
        return self._allocated_time

    @allocated_time.setter
    def allocated_time(self, allocated_time):
        """Sets the allocated_time of this SubmittedTaskInfoExt.


        :param allocated_time: The allocated_time of this SubmittedTaskInfoExt.  # noqa: E501
        :type: float
        """

        self._allocated_time = allocated_time

    @property
    def allocated_core_ids(self):
        """Gets the allocated_core_ids of this SubmittedTaskInfoExt.  # noqa: E501


        :return: The allocated_core_ids of this SubmittedTaskInfoExt.  # noqa: E501
        :rtype: list[str]
        """
        return self._allocated_core_ids

    @allocated_core_ids.setter
    def allocated_core_ids(self, allocated_core_ids):
        """Sets the allocated_core_ids of this SubmittedTaskInfoExt.


        :param allocated_core_ids: The allocated_core_ids of this SubmittedTaskInfoExt.  # noqa: E501
        :type: list[str]
        """

        self._allocated_core_ids = allocated_core_ids

    @property
    def start_time(self):
        """Gets the start_time of this SubmittedTaskInfoExt.  # noqa: E501


        :return: The start_time of this SubmittedTaskInfoExt.  # noqa: E501
        :rtype: datetime
        """
        return self._start_time

    @start_time.setter
    def start_time(self, start_time):
        """Sets the start_time of this SubmittedTaskInfoExt.


        :param start_time: The start_time of this SubmittedTaskInfoExt.  # noqa: E501
        :type: datetime
        """

        self._start_time = start_time

    @property
    def end_time(self):
        """Gets the end_time of this SubmittedTaskInfoExt.  # noqa: E501


        :return: The end_time of this SubmittedTaskInfoExt.  # noqa: E501
        :rtype: datetime
        """
        return self._end_time

    @end_time.setter
    def end_time(self, end_time):
        """Sets the end_time of this SubmittedTaskInfoExt.


        :param end_time: The end_time of this SubmittedTaskInfoExt.  # noqa: E501
        :type: datetime
        """

        self._end_time = end_time

    @property
    def node_type(self):
        """Gets the node_type of this SubmittedTaskInfoExt.  # noqa: E501


        :return: The node_type of this SubmittedTaskInfoExt.  # noqa: E501
        :rtype: ClusterNodeTypeForTaskExt
        """
        return self._node_type

    @node_type.setter
    def node_type(self, node_type):
        """Sets the node_type of this SubmittedTaskInfoExt.


        :param node_type: The node_type of this SubmittedTaskInfoExt.  # noqa: E501
        :type: ClusterNodeTypeForTaskExt
        """

        self._node_type = node_type

    @property
    def error_message(self):
        """Gets the error_message of this SubmittedTaskInfoExt.  # noqa: E501


        :return: The error_message of this SubmittedTaskInfoExt.  # noqa: E501
        :rtype: str
        """
        return self._error_message

    @error_message.setter
    def error_message(self, error_message):
        """Sets the error_message of this SubmittedTaskInfoExt.


        :param error_message: The error_message of this SubmittedTaskInfoExt.  # noqa: E501
        :type: str
        """

        self._error_message = error_message

    @property
    def cpu_hyper_threading(self):
        """Gets the cpu_hyper_threading of this SubmittedTaskInfoExt.  # noqa: E501


        :return: The cpu_hyper_threading of this SubmittedTaskInfoExt.  # noqa: E501
        :rtype: bool
        """
        return self._cpu_hyper_threading

    @cpu_hyper_threading.setter
    def cpu_hyper_threading(self, cpu_hyper_threading):
        """Sets the cpu_hyper_threading of this SubmittedTaskInfoExt.


        :param cpu_hyper_threading: The cpu_hyper_threading of this SubmittedTaskInfoExt.  # noqa: E501
        :type: bool
        """

        self._cpu_hyper_threading = cpu_hyper_threading

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SubmittedTaskInfoExt, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SubmittedTaskInfoExt):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
